# docker-compose.yml

version: '3.7'

services:
  api:
    build:
      dockerfile: Dockerfile
    command: python src/main.py
    container_name: api
    volumes:
      - ../:/api
    ports:
      - 8008:8008
    environment:
      - DATABASE_URL=competicoes.db
